version: 2.1

orbs:
  anchore: anchore/anchore-engine@dev:0.1.0
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build Docker image
          command: |
            docker build -t ${CIRCLE_PROJECT_REPONAME}:ci -f .circleci/Dockerfile .
      - run:
          name: Save Docker image
          command: |
            rm -rf ~/workspace/caches/
            mkdir ~/workspace/caches/ -p
            docker save -o ~/workspace/caches/${CIRCLE_PROJECT_REPONAME}-ci.tar ${CIRCLE_PROJECT_REPONAME}:ci
      - persist_to_workspace:
          root: ~/workspace/
          paths:
            - caches/*

  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - attach_workspace:
          at: ~/workspace/
      - run:
          name: Load Docker image layer cache
          command: |
            docker load -i ~/workspace/caches/${CIRCLE_PROJECT_REPONAME}-ci.tar
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci

workflows:
  scan_image:
    jobs:
      - build
      - local_image_scan:
          requires:
            - build
      - anchore/image_scan:
          image_name: 'anchore/anchore-engine:latest'
      - anchore/image_scan:
          image_name: 'anchore/private_testing:anchore-ui-dev'
          private_registry: True
          timeout: '500'
